logo_orangeHRM = "xpath://div[@id='divLogo']//img"
txt_account = "xpath://span[contains(text(),'( Username : Admin | Password : admin123 )')]"
logo_hrForAll_1 = "xpath://*[name()='circle' and contains(@fill,'url(#g)')]"
logo_hrForAll_2 = "xpath://*[name()='image' and contains(@overflow,'visible')]"
logo_hrForAll_3 = "xpath://*[name()='circle' and contains(@fill,'url(#f)')]"
txt_loginPanel = "id:logInPanelHeading"
background_txt_loginPanel = "xpath://*[name()='path' and contains(@fill,'url(#d)')]"
txt_username = "id:txtUsername"
txt_hint_username = "xpath://span[@class='form-hint'][contains(text(),'Username')]"
icon_person = "xpath://*[name()='g' and contains(@fill,'gray')]"
txt_password = "id:txtPassword"
txt_hint_password = "xpath://span[@class='form-hint'][contains(text(),'Password')]"
icon_password = "xpath://*[name()='path' and contains(@fill,'gray')]"
btn_login = "id:btnLogin"
background_btn_login = "xpath://*[name()='path' and contains(@fill,'url(#l)')]"
txt_errorMessage = "id:spanMessage"
link_forgotPassword = "xpath://a[contains(text(),'Forgot your password?')]"
txt_footer = "xpath://div[contains(text(),'OrangeHRM 4.10.1')]"
link_footer = "xpath://a[contains(text(),'OrangeHRM, Inc')]"
btn_linkedin = "xpath://a[1]//img[1]"
btn_facebook = "xpath://a[2]//img[1]"
btn_twitter = "xpath://a[3]//img[1]"
btn_youtube = "xpath://a[4]//img[1]"
